/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root.tsx';
import { Route as SignalRouteImport } from './routes/signal.tsx';
import { Route as SearchParamsRouteImport } from './routes/search-params.tsx';
import { Route as RealisticRouteImport } from './routes/realistic.tsx';
import { Route as NaiveRouteImport } from './routes/naive.tsx';
import { Route as MemoizedRouteImport } from './routes/memoized.tsx';
import { Route as ContextRouteImport } from './routes/context.tsx';
import { Route as BetterRouteImport } from './routes/better.tsx';
import { Route as IndexRouteImport } from './routes/index.tsx';
import { Route as MapIndexRouteImport } from './routes/map/index.tsx';

const SignalRoute = SignalRouteImport.update({
  id: '/signal',
  path: '/signal',
  getParentRoute: () => rootRouteImport,
} as any);
const SearchParamsRoute = SearchParamsRouteImport.update({
  id: '/search-params',
  path: '/search-params',
  getParentRoute: () => rootRouteImport,
} as any);
const RealisticRoute = RealisticRouteImport.update({
  id: '/realistic',
  path: '/realistic',
  getParentRoute: () => rootRouteImport,
} as any);
const NaiveRoute = NaiveRouteImport.update({
  id: '/naive',
  path: '/naive',
  getParentRoute: () => rootRouteImport,
} as any);
const MemoizedRoute = MemoizedRouteImport.update({
  id: '/memoized',
  path: '/memoized',
  getParentRoute: () => rootRouteImport,
} as any);
const ContextRoute = ContextRouteImport.update({
  id: '/context',
  path: '/context',
  getParentRoute: () => rootRouteImport,
} as any);
const BetterRoute = BetterRouteImport.update({
  id: '/better',
  path: '/better',
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const MapIndexRoute = MapIndexRouteImport.update({
  id: '/map/',
  path: '/map/',
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/better': typeof BetterRoute;
  '/context': typeof ContextRoute;
  '/memoized': typeof MemoizedRoute;
  '/naive': typeof NaiveRoute;
  '/realistic': typeof RealisticRoute;
  '/search-params': typeof SearchParamsRoute;
  '/signal': typeof SignalRoute;
  '/map': typeof MapIndexRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/better': typeof BetterRoute;
  '/context': typeof ContextRoute;
  '/memoized': typeof MemoizedRoute;
  '/naive': typeof NaiveRoute;
  '/realistic': typeof RealisticRoute;
  '/search-params': typeof SearchParamsRoute;
  '/signal': typeof SignalRoute;
  '/map': typeof MapIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/better': typeof BetterRoute;
  '/context': typeof ContextRoute;
  '/memoized': typeof MemoizedRoute;
  '/naive': typeof NaiveRoute;
  '/realistic': typeof RealisticRoute;
  '/search-params': typeof SearchParamsRoute;
  '/signal': typeof SignalRoute;
  '/map/': typeof MapIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/better'
    | '/context'
    | '/memoized'
    | '/naive'
    | '/realistic'
    | '/search-params'
    | '/signal'
    | '/map';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/better'
    | '/context'
    | '/memoized'
    | '/naive'
    | '/realistic'
    | '/search-params'
    | '/signal'
    | '/map';
  id:
    | '__root__'
    | '/'
    | '/better'
    | '/context'
    | '/memoized'
    | '/naive'
    | '/realistic'
    | '/search-params'
    | '/signal'
    | '/map/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  BetterRoute: typeof BetterRoute;
  ContextRoute: typeof ContextRoute;
  MemoizedRoute: typeof MemoizedRoute;
  NaiveRoute: typeof NaiveRoute;
  RealisticRoute: typeof RealisticRoute;
  SearchParamsRoute: typeof SearchParamsRoute;
  SignalRoute: typeof SignalRoute;
  MapIndexRoute: typeof MapIndexRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signal': {
      id: '/signal';
      path: '/signal';
      fullPath: '/signal';
      preLoaderRoute: typeof SignalRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/search-params': {
      id: '/search-params';
      path: '/search-params';
      fullPath: '/search-params';
      preLoaderRoute: typeof SearchParamsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/realistic': {
      id: '/realistic';
      path: '/realistic';
      fullPath: '/realistic';
      preLoaderRoute: typeof RealisticRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/naive': {
      id: '/naive';
      path: '/naive';
      fullPath: '/naive';
      preLoaderRoute: typeof NaiveRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/memoized': {
      id: '/memoized';
      path: '/memoized';
      fullPath: '/memoized';
      preLoaderRoute: typeof MemoizedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/context': {
      id: '/context';
      path: '/context';
      fullPath: '/context';
      preLoaderRoute: typeof ContextRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/better': {
      id: '/better';
      path: '/better';
      fullPath: '/better';
      preLoaderRoute: typeof BetterRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/map/': {
      id: '/map/';
      path: '/map';
      fullPath: '/map';
      preLoaderRoute: typeof MapIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BetterRoute: BetterRoute,
  ContextRoute: ContextRoute,
  MemoizedRoute: MemoizedRoute,
  NaiveRoute: NaiveRoute,
  RealisticRoute: RealisticRoute,
  SearchParamsRoute: SearchParamsRoute,
  SignalRoute: SignalRoute,
  MapIndexRoute: MapIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
